<?php 
//For Gesoftlabs
//$MAP_API_KEY = "ABQIAAAAdK6ao51Z3gyHSqh7HcUSlxRnsO5XZpvZAJWs1D7Ji7eDq8ORsxQeITa6NYtM0cctYVZ0ztoY_-7neQ";
//For mannestate
//$MAP_API_KEY = "ABQIAAAAdK6ao51Z3gyHSqh7HcUSlxSxBNNvNNdCbZlOvmBDKh9t8J9G9RQKuPzYNLRKB4czen6jCoEDHxIPnw";
//$AJAX_API_KEY = "ABQIAAAAdK6ao51Z3gyHSqh7HcUSlxSxBNNvNNdCbZlOvmBDKh9t8J9G9RQKuPzYNLRKB4czen6jCoEDHxIPnw";
//For Localhost
$MAP_API_KEY = "ABQIAAAAdK6ao51Z3gyHSqh7HcUSlxRea9oQE2_LSz4Cqp4Ay3VG8oNAeBS3FFpByS_4XFTe0iUos3ZAc4iccg";

$AJAX_API_KEY = "ABQIAAAAdK6ao51Z3gyHSqh7HcUSlxRea9oQE2_LSz4Cqp4Ay3VG8oNAeBS3FFpByS_4XFTe0iUos3ZAc4iccg";

$MISREPRESENTATION_ACT='';

$DEFAULT_BRIEF_DESCRIPTION = "Building/Renovation project."
?>